test:
  server_base_url: 'http://localhost:3000/'
  client_id: ''
  client_secret: ''

development:
  server_base_url: 'http://localhost:3000/'
  client_id: '5561b138c4da518dec8f680eba1ff06be68a4d7d3d33fa2f15284c98cbadfe0f'
  client_secret: '533ecdd7efd1c292f5890d8ceb5850a00e19e942cf40e60e67552c6ad5a0d8ba'

production:
  server_base_url: 'http://localhost:3000/'
  client_id: 'hola'
  client_secret: 'sahed'
